#!/bin/bash

# Function to read CPU times from /proc/stat
read_cpu_stats() {
    grep '^cpu[0-9]' /proc/stat | awk '
    {
        core=$1;
        total=0;
        for (i=2; i<=NF; i++) total+=$i;
        idle=$5;
        print core, total, idle;
    }'
}

# Read initial CPU stats
declare -A total1 idle1
while read -r core t i; do
    total1[$core]=$t
    idle1[$core]=$i
done < <(read_cpu_stats)

# Wait for 1 second
sleep 1

# Read CPU stats again
declare -A total2 idle2
while read -r core t i; do
    total2[$core]=$t
    idle2[$core]=$i
done < <(read_cpu_stats)

# Build and print output on a single line
output=""
for i in $(seq 0 11); do
    core="cpu$i"
    delta_total=$(( total2[$core] - total1[$core] ))
    delta_idle=$(( idle2[$core] - idle1[$core] ))
    usage=$(awk "BEGIN {printf \"%.1f\", (1 - ($delta_idle / $delta_total)) * 100}")
    output+=" [$i] ${usage}%"
done

echo "$output"
